title: Career Goals!
author: kevinencarnacion
email: kevinaencarnacion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My career goals in web development, presently centered
  around developing a portfolio and expanding my knowledge whilst
  utilizing GitHub to its fullest potential.

# social links
twitter_username: turalosk # DO NOT include the @ character, or else the build will fail!
github_username:  kevin encarnacion # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
